version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: locadora
    environment:
      POSTGRES_DB: locadora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
